delay_after_panel: 0.5
delay_after_teleport: 1.0
delay_after_channel: 5.0
positions_by_channel:
  1:
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
  2:
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
  3:
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
  4:
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
  5:
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
  6:
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
  7:
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
  8:
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]
channel_buttons:
  1: [0, 0]
  2: [0, 0]
  3: [0, 0]
  4: [0, 0]
  5: [0, 0]
  6: [0, 0]
  7: [0, 0]
  8: [0, 0]
